### ISSUE TITLE
some question about VisualAdapter in AVS

### ISSUE THREAD

**Issue by Divine0719** [GenjiB/LAVISH#15]
Hello，
You added rep_token to the calclation of  the VisualAdapter in AVS.
I print the max of value during this process as shown in the Fig.
I can't understand why the value changed from **zero to non-zero** value after **softmax operation.**
If it is zero, what is its effection to the whole model?
Thanks~
![2](https://github.com/GenjiB/LAVISH/assets/77132276/2043f580-1451-4df8-9343-ec9d7da3f228)
![1](https://github.com/GenjiB/LAVISH/assets/77132276/a7a6db48-f8df-4a6a-989e-adff27b06938)

**Comment by GenjiB** [comment]
Sorry for the confusion. In the paper, we indicate the tokens are randomly initialized. However, we implement it in zero-initialization for AVS and AVQA.

**Comment by Divine0719** [comment]
> 
Many thanks~
