### ISSUE TITLE
cannot get the claimed accuracy in audio-visual event localization.

### ISSUE THREAD

**Issue by woshihaozhu** [GenjiB/LAVISH#2]
I use the default config in this repo to train AVE task without any modification. But the accuracy obtained is not the same as the reported in the paper.  I'm a bit confused about this. **Swin-V2 Large** is also taken as the visual and audio encoder, but the best precision  I get  is 78.8, while the paper is 81.1.

**Training shell**
`python3 main_trans.py --Adapter_downsample=8 --audio_folder=data/AVE_audio --batch_size=2 --early_stop=5 --epochs=50 \
--is_audio_adapter_p1=1 --is_audio_adapter_p2=1 --is_audio_adapter_p3=0 --is_before_layernorm=1 --is_bn=1 --is_fusion_before=1 \
--is_gate=1 --is_post_layernorm=1 --is_vit_ln=0 --lr=5e-05 --lr_mlp=4e-06 --mode=train \
--num_conv_group=2 --num_tokens=2 --num_workers=16 --video_folder=data/AVE_video_frames  \
--is_multimodal=1 --vis_encoder_type=swin --wandb=1`

**Comparision**
![image](https://user-images.githubusercontent.com/35716657/209436501-62cbfe8b-7c58-4eb0-a264-79f0af5ce185.png)
![image](https://user-images.githubusercontent.com/35716657/209436507-2065121f-300f-40b5-8bce-2107a61a25d4.png)

**Comment by GenjiB** [comment]
Thanks for the feedback. The gap is huge. Let me check if there is any bug.

**Comment by GenjiB** [comment]
@woshihaozhu  Thanks for the feedback. The old codes do not have audio-visual latent token compression (see eq 7).
I also notice the old code should achieve ~79.3% accuracy. I uploaded the preprocessed data on Huggingface. You can download it if needed. 
![image](https://user-images.githubusercontent.com/32382292/209534949-bca76618-bcf4-4d09-8aac-692d1fb1b011.png)

**Comment by abdurad** [comment]
With the preprocessed data in Huggingface, the accuracy still 79.05%!!!
