### ISSUE TITLE
For audio, you use both .wav format and .npy. Here is a dimensional error in the code. 

### ISSUE THREAD

**Issue by Bravo5542** [GenjiB/LAVISH#3]
File "/home/LAVisH/LAVISH-main/AVQA/net_grd_avst/net_avst.py", line 317, in forward
    audio = repeat(audio, 'b t len dim -> b t c len dim', c=3)
  File "/home/anaconda3/envs/lavish/lib/python3.8/site-packages/einops/einops.py", line 537, in repeat
    return reduce(tensor, pattern, reduction='repeat', **axes_lengths)
  File "/home/anaconda3/envs/lavish/lib/python3.8/site-packages/einops/einops.py", line 418, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing repeat-reduction pattern "b t len dim -> b t c len dim".
 Input tensor shape: torch.Size([1, 10, 128]). Additional info: {'c': 3}.
 Expected 4 dimensions, got 3

**Comment by Bravo5542** [comment]
Here is another dimensional error：
`File "AVQA/net_grd_avst/net_avst.py", line 376, in forward
    visual_posi = rearrange(visual_posi, '(b t) (h w) c -> b t c h w', b=bs ,t=t, h=6 ,w=6)`
`einops.EinopsError:  Error while processing rearrange-reduction pattern "(b t) (h w) c -> b t c h w".
 Input tensor shape: torch.Size([10, 3, 192, 192]). Additional info: {'b': 1, 't': 10, 'h': 6, 'w': 6}.
 Expected 3 dimensions, got 4`

**Comment by GenjiB** [comment]
I'm going to update these in the next few days. Thanks.

**Comment by Bravo5542** [comment]
Thank u for ur excellent work!
