### ISSUE TITLE
cannot get the claimed mIOU in audio-visual segmentation.

### ISSUE THREAD

**Issue by woshihaozhu** [GenjiB/LAVISH#5]
There also remains the performance gap between the mIOU i got and the reported in the paper. Shown below are my training results and the paper's results. 

![image](https://user-images.githubusercontent.com/35716657/209488077-fc2ac276-ab76-45ac-b603-3df626bfc0e5.png)

![image](https://user-images.githubusercontent.com/35716657/209487962-c56c12c7-8b49-4b65-ace6-a662f8cb8e7a.png)

**Comment by GenjiB** [comment]
I found the code will use multi-GPUs. Try to use a single GPU. It would be ~0.5 miou difference. I'm also checking if there is any buy.

**Comment by woshihaozhu** [comment]
Yeah, I used 3-GPUS to train the model. How much GPU shoud be better?

**Comment by GenjiB** [comment]
just one GPU. I got ~79.7 for current codes. I'm checking if I've changed something important.

The best model was like
![image](https://user-images.githubusercontent.com/32382292/209598736-7ce736cc-b029-4e06-829c-7b1205ed349a.png)

**Comment by woshihaozhu** [comment]
I strongly suggest that the author could pull out the VisualAdapter from the three tasks and make it a common module, instead of each task needing to be embedded. This way not only the code is tidy, but also the problem can be easily found.
