### ISSUE TITLE
Is this the true config?

### ISSUE THREAD

**Issue by Rainlt** [GenjiB/LAVISH#7]
In the readme file of AVQA task, you have provided the command to train the model. 

"python3 net_grd_avst/main_avst.py --Adapter_downsample=8 --audio_dir=/data/yanbo/Dataset/AVQA/vggish --batch-size=1 --early_stop=5 --epochs=30 --is_before_layernorm=1 --is_bn=0 --is_gate=1 --is_multimodal=1 --is_post_layernorm=1 --is_vit_ln=1 --lr=8e-05 --lr_block=3e-06 --num_conv_group=4 --num_tokens=64 --num_workers=16 --video_res14x14_dir=/data/yanbo/Dataset/AVQA/ --wandb=1“

You only used 1 sample per batch? Or we could use the command in train.sh to reproduce the result?

**Comment by GenjiB** [comment]
Sorry for the confusion. The parameters in train.sh are for debugging. You can just run the command I provided. It took about 20GB GPU memory.  Let me know if you have further questions.
